server:
  port: 9090
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/taskmanagement
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    database: postgresql
    show-sql: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
